version: '3.8'

services:
  nua:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nua-app
    restart: unless-stopped
    
    ports:
      - "4323:4323"
    
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=INFO
      - UNIFI_RETRY_ATTEMPTS=5
      - UNIFI_RETRY_DELAY=5000
    
    volumes:
      # Persist database and logs
      - nua_data:/usr/src/app/server/config
      # Optional: Mount configuration from host
      # - ./server/config:/usr/src/app/server/config
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4323/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    
    networks:
      - nua-network

  # Optional: Add a reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   container_name: nua-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     # Add SSL certificates if using HTTPS
  #     # - ./certs:/etc/ssl/certs:ro
  #   depends_on:
  #     - nua
  #   networks:
  #     - nua-network

volumes:
  nua_data:
    driver: local

networks:
  nua-network:
    driver: bridge