name: Docker Image CI

on:
  push:
    branches: [ "**" ]  # Build on any branch
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract version from date
      id: version
      run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Set Docker repository
      id: repo
      run: |
        # Use GitHub repository owner/name (converts to lowercase for Docker Hub compatibility)
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "DOCKER_REPO=${REPO_NAME}" >> $GITHUB_ENV
        echo "Using Docker repository: ${REPO_NAME}"

    # DEBUG
    # - name: Output environment variables
    #   run: printenv

    - name: Build and push the Docker image (master branch)
      if: github.ref_name == 'master'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REPO }}:latest
          ${{ env.DOCKER_REPO }}:${{ env.VERSION }}

    - name: Build and push the Docker image (other branches)
      if: github.ref_name != 'master'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REPO }}:dev
          ${{ env.DOCKER_REPO }}:${{ env.VERSION }}

    # - name: Output image version tag
    #   run: |
    #     echo "Docker image version: $VERSION"